jwt:
  secret: dashkjasdhjadlshldkashldasghjasgasajksdhksdahkdashakdhdaslhsdlhasdlhadklshdlashlasdkhdlashdlshdlsahladshldashlasddasbjasdhjdashasdkhasdjkhasdkashkhlasdhsdal

  access:
    expiration: 80
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh